type = "checkout_ui_extension"
name = "free-gift-ui"

extension_points = [
  'Checkout::Dynamic::Render'
]

[capabilities]
api_access = true

[[metafields]]
namespace = "free-gift"
key = "products"

[settings]
  [[settings.fields]]
  key = "banner_title"
  type = "single_line_text_field"
  name = "Banner title"
  description = "Enter a title for the banner"
